import { useEffect, useState } from "react";
import { User } from "../../types/others";
import { deleteUserAvatar, getUserAvatar } from "../../api/api.user";
import { getUser, getUserFromStorage } from "../../utils/userAuthentication";
import EditableField from "../inputs/EditableField";
import Avatar from "../common/Avatar";
import AvatarCropModal from "../modals/CropAvatarModal";
import { useAlert } from "../../contexts/AlertContext";
import { twoWayGenderMap, twoWayRoleMap } from "../../constants/maps";
import { getDateFormatter } from "../../utils/formatters";